### ISSUE TITLE
nwsapi v2.2.18 causes "querySelectorAll(...).includes is not a function" error in jsdom / React tests

### ISSUE THREAD

**Issue by MattFixesFaults** [dperini/nwsapi#143]
After updating some packages in our project, our React tests began failing with the following error:

```TypeError: e.parentElement.querySelectorAll(...).includes is not a function```

After some investigation, I discovered that this error started occurring when our dependency tree shifted from using nwsapi v2.2.16 to nwsapi v2.2.18. Pinning nwsapi to version 2.2.16 via resolutions in our package.json resolved the issue, which indicates that something in v2.2.18 is causing incompatibility in our test environment.

Steps to Reproduce:

Set up a React project using jsdom with @testing-library/react and @testing-library/user-event.
Use a component that renders Ant Design's DatePicker (or a similar component that indirectly uses nwsapi).
Run tests that interact with the DatePicker (e.g., triggering clicks on the input).
Observe the error:
TypeError: e.parentElement.querySelectorAll(...).includes is not a function
Environment:

jest-environment-jsdom: 29.7.0
@testing-library/react: 16.2.0
@testing-library/user-event: 14.6.1
nwsapi: Updated from 2.2.16 to 2.2.18
antd: 5.22.5
react: 18.2.0

Workaround:
Pinning nwsapi to version 2.2.16 using the following resolution in our package.json fixed the error:

```
"resolutions": {
  "nwsapi": "2.2.16"
}
```

Expected Behavior:
nwsapi should not break the DOM querying behavior when used in jsdom or when invoked through libraries like @testing-library/user-event. Ideally, the change in version should be backwards-compatible or provide a migration path.

Additional Context:
The error originates from internal calls (in nwsapi and jsdom's style handling) that assume querySelectorAll returns an object with an .includes method. Since NodeLists in jsdom do not have .includes (and a polyfill in our setup didn't resolve the issue with the new version), it appears that nwsapi v2.2.18 might have introduced a change causing this problem.

I appreciate any help or guidance on this matter. Please let me know if further information is needed.

**Comment by dperini** [comment]
@MattFixesFaults 
the bug affecting your testin environment is confirmed and it is affecting others too.
The problem is blindly trusting "e.parentElement" to always exist which is not the case for the document node.
This will be fixed shortly with a new release, however keep in mind that the :has() selector resolver is not ready for consumption yet.

Thank you for chiming in and making notice of the problem.

**Comment by KindaOK** [comment]
This bug was fixed by #141, but that change hasn't been released yet

**Comment by MattFixesFaults** [comment]
I can confirm this is fixed! Thanks for the quick turn around 👍

**Comment by danielrentz** [comment]
I still see problems in our unit tests using jquery and jsdom, starting with nwsapi 2.2.18, AND still existing in 2.2.19.

Please check in this repro:
https://stackblitz.com/edit/stackblitz-starters-v94hftfh
Run `node index.js`. The second assertion fails with 2.2.18, but works with 2.2.16.

I do not know if this related, or if it's better to create another issue...

**Comment by KindaOK** [comment]
I think it's the changes to `:scope` (and maybe also the `:has` selector again?) that did this. I added `console.log` to the result of `compileSelector` and dumped that out below

<details>
<summary> selector + compile code output </summary>
```
_matches
*
source
r=true;
_querySelectorAll
:scope
source
if(e===(s.from.nodeType===9?s.root:s.from)){r[++j]=c[k];continue main;}
_querySelectorAll
:has(*,:jqfake)
source
if(e.querySelector(":scope *,:jqfake")){r[++j]=c[k];continue main;}
_querySelectorAll
:scope *,:jqfake
source
var N2=e;while(e&&(e=e.parentElement)){if(e===(s.from.nodeType===9?s.root:s.from)){r[++j]=c[k];continue main;}}e=N2;
_querySelectorAll
[selected]
source
if((e.hasAttribute&&e.hasAttribute("selected"))){r[++j]=c[k];continue main;}
_querySelectorAll
[id~=jQuery3710885966201177788-]
source
if(((/(^|\s)jQuery3710885966201177788-(\s|$)/).test(e.getAttribute&&e.getAttribute("id"))==true)){r[++j]=c[k];continue main;}
_querySelectorAll
a#jQuery3710885966201177788+*
source
var N3=e;if(e&&(e=e.previousElementSibling)){if((/^jQuery3710885966201177788$/.test(e.getAttribute("id")))){if((e.localName=="a")){r[++j]=c[k];continue main;}}}e=N3;
_querySelectorAll
:checked
source
if((/^input$/i.test(e.localName)&&("|radio|checkbox|".includes("|"+e.type+"|")&&e.checked)||(/^option$/i.test(e.localName)&&(e.selected||e.checked)))){r[++j]=c[k];continue main;}
_querySelectorAll
:disabled
source
if((("form" in e||/^optgroup$/i.test(e.localName))&&"disabled" in e)){var x=0,N=[],F=false,L=false;if(!(/^(optgroup|option)$/i.test(e.localName))){n=e.parentElement;while(n){if(n.localName=="fieldset"){N[x++]=n;if(n.disabled===true){F=true;break;}}n=n.parentElement;}for(var x=0;x<N.length;x++){if((n=s.first("legend",N[x]))&&n.contains(e)){L=true;break;}}}if(e.disabled===true||(F&&!L)){r[++j]=c[k];continue main;}}
_querySelectorAll
legend
source
r[++j]=c[k];continue main;
_querySelectorAll
legend
_querySelectorAll
[name='']
source
if((e.getAttribute&&e.getAttribute("name")=="")){r[++j]=c[k];continue main;}
_querySelectorAll
:scope >*>.t
source
var N4=e;if(e&&(e=e.parentElement)){var N2=e;if(e&&(e=e.parentElement)){if(e===(s.from.nodeType===9?s.root:s.from)){r[++j]=c[k];continue main;}}e=N2;}e=N4;
_querySelectorAll
script
_querySelectorAll
:scope >*>.t
```
</details>

@dperini Yeah the draft PR (#131) I had did (that seems to have been the basis of the new `:scope` changes) had some issues with the WPT scope tests, even the ones that shouldn't have had problems because they didn't include `:has`. I didn't understand why things were going wrong though and eventually kinda gave up.

**Comment by dperini** [comment]
The specified error has been fixed but the for the :has() pseudo-class is not yet complete.
I am closing this because it refers to the error which has been already fixed.
Refer to the :has() pseudo-class issues for incomplete support.
