### ISSUE TITLE
"'button#test-btn.sm,,,Ahidden' is not a valid selector" if first class entry contains colon

### ISSUE THREAD

**Issue by jklingen** [dperini/nwsapi#153]
The error is occurring in an environment that uses Jest, testing-library, tailwind.css and others - and only if the element to be selected (in this case, via `screen.getByRole()`) has a colon in the first class entry (e.g. `class="sm:hidden foo"`). After flipping the classes, the error does not occur.

Affected versions: 2.2.21 and 2.2.22 (had no issues with 2.2.20)

After inspecting at a breakpoint, the issue seems to be that class entry is URL-encoded to `sm%3Ahidden` in nwsapi, which then ends up as `sm,,,Ahidden` in the selector.

The issue is probably related to what two other users describe here:
* https://github.com/dperini/nwsapi/issues/152#issuecomment-3190193311
* https://github.com/dperini/nwsapi/issues/152#issuecomment-3266860810

Since I am not using nwsapi directly, I wasn't able to create a minimal reproduction with reasonable effort. So I asked AI, and here's what they came up with. I don't know for sure whether that's how nwsapi is to be used; anyway, I hope it helps for a better understanding of what's happening.

```
const { JSDOM } = require('jsdom');
const nwsapi = require('nwsapi');
const domInstance = new JSDOM('<!DOCTYPE html><body><button class="sm:hidden" id="test-btn">Test</button></body>');
const { window } = domInstance;
const { document } = window;

const dom = nwsapi(window);
const btn = document.getElementById('test-btn');
dom.select(':scope', btn);


```

**Comment by xemlock** [comment]
Similar issue happens if `id` in selector starts with a number. Instead of number being escaped, `#` gets replaced with commas - the following input:

```css
input#6jjqUym3MsrtbtDEMLtShL_checkbox.sc-fhfEft >.sc-fhfEft:focus-visible
```

results in:

```
SyntaxError: 'input,,,jjqUym3MsrtbtDEMLtShL_checkbox.sc-fhfEft >.sc-fhfEft:focus-visible' is not a valid selector
```

**Comment by dperini** [comment]
@jeremy-daley-kr 
thank you for the help with this issue and for the details you provided.
I will investigate this during the weekend and be back to you to check if the solution does work.
It seems the problem is bound to how the :scope selector changed from a simple substitution to a real pseudo-class resolver.

**Comment by dperini** [comment]
This issue should be fixed by [6b27300](https://github.com/dperini/nwsapi/commit/6b273003dc7a8a0d729c6267c04e41d8597f3b2d) in release 2.2.23.
Thank you all for the reporting and for the useful description and test cases.

**Comment by axkom** [comment]
Error is still reproducing for selectors with colon `:` in the name in version 2.2.23.

```
    SyntaxError: 'span#banner-description-:r0,,.Box-rui__sc-1475jr3-0 [data-rui="toolbox"]' is not a valid selector

      50 |
    > 51 |     const alertsLink = screen.getByRole('link', { name: 'alert' })
```

Original element

```
<span
    id="banner-description-:r0:"
    class="Box-rui__sc-1475jr3-0 Text-rui__sc-1mtagir-0 benldS gLyhiv"
  >
Some descritpion 

    <a class="Box-rui__sc-1475jr3-0 Text-rui__sc-1mtagir-0 Link__StyledText-rui__sc-1ykr1od-0 gFJIGA enTJkF eMrqqr" href="/here">
      <span class="Box-rui__sc-1475jr3-0 Text-rui__sc-1mtagir-0 gCpKip">alert</span>
    </a>
</span>
```

**Comment by xemlock** [comment]
The snippet I've posted [earlier in this thread](https://github.com/dperini/nwsapi/issues/153#issuecomment-3300537157) still fails on `2.2.23` with the same error. Although the selector doesn't contain colon, I believe it's caused by the same underlying issue.
