### ISSUE TITLE
2.0.9->2.1.0 upgrade breaks querySelector call with attribute selectors

### ISSUE THREAD

**Issue by Macil** [dperini/nwsapi#24]
```js
'use strict';
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const dom = new JSDOM(`
<div aria-label="Account Information">
  <a href="https://www.example.com/foo" target="_blank">Foo</a>
</div>
`);

const els = dom.window.document.querySelectorAll(
  'div[aria-label] a[href="https://www.example.com/foo"]'
);
console.log(els);
```

With jsdom 13.2.0 and nwsapi 2.0.9, this code correctly finds one element. With nwsapi 2.1.0, this code fails to find any elements.

I noticed that nwsapi 2.1.0 fixes https://github.com/jsdom/jsdom/issues/2403, which also has to do with attribute selectors, so I wonder if that fix might be related to this issue.

**Comment by dperini** [comment]
This should have been fixed by the new default setting of LIVECACHE changed to false.
Closing the issue. Thank you for reporting the problem.

**Comment by Macil** [comment]
I still see this problem with nwsapi 2.1.1.

This example doesn't have any elements change in it, so it's not clear to me that the livecache setting should affect it.

**Comment by dperini** [comment]
@Macil thank you for reporting back the persisting issue.
Actually the issue you reported was not due to the caching bug, it was a different problem.
If you can check back with the latest commit I did and report if it completely fix your issue.
It is extremely important this issue get fixed and I would need to add tests against future regressions since it was not easy to find the problem after so many changes.
Thank you again for your precious help, really appreciated.

**Comment by Macil** [comment]
I've just tested it with master, and it looks like it's fixed.

**Comment by dperini** [comment]
@Macil thank you for the testing you did and for reporting the issue.
Closing the issue.
