### ISSUE TITLE
v2.2.3 DOMException [SyntaxError]: '.disabled):not(:disabled)' is not a valid selector

### ISSUE THREAD

**Issue by jdufresne** [dperini/nwsapi#81]
The following selector was used successfully in v2.2.2 but raises a syntax error v2.2.3:

```css
[data-bs-toggle="dropdown"]:not(.disabled):not(:disabled)
```

This selector is used by the Bootstrap library:

https://github.com/twbs/bootstrap/blob/3d84e60d690b9755d29f2a8bb9ca807f484768bd/js/src/dropdown.js#L55

Script to reproduce:

```js
const jsdom = require('jsdom');

const dom = new jsdom.JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
dom.window.document.querySelectorAll('[data-bs-toggle="dropdown"]:not(.disabled):not(:disabled)');
```

```
$ node test.js

.../node_modules/nwsapi/src/nwsapi.js:559
        throw err;
        ^
DOMException [SyntaxError]: '.disabled):not(:disabled)' is not a valid selector
    at emit (.../node_modules/nwsapi/src/nwsapi.js:557:17)
    at Object._matches [as match] (.../node_modules/nwsapi/src/nwsapi.js:1400:9)
    at Array.Resolver (eval at compile (.../node_modules/nwsapi/src/nwsapi.js:760:17), <anonymous>:3:105)
    at collect (.../node_modules/nwsapi/src/nwsapi.js:1552:21)
    at Object._querySelectorAll [as select] (.../node_modules/nwsapi/src/nwsapi.js:1509:36)
    at DocumentImpl.querySelectorAll (.../node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:78:26)
    at Document.querySelectorAll (.../node_modules/jsdom/lib/jsdom/living/generated/Document.js:1051:58)
    at Object.<anonymous> (.../test.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

Node.js v18.15.0
```

**Comment by flannanl** [comment]
I'm seeing the same issue after moving up to v2.2.3. In my case, I have 3 `:not()`.

`.main-nav:not(.header-nav):not(.settings-nav):not(.other-nav)`

**Comment by ankursehdev** [comment]
Having same issue via JsDOM.

**Comment by dperini** [comment]
@jdufresne & all
The issue should be resolved in release 2.2.4.
Please review and confirm that everything works.
Thank you for submitting a reproducible code showing the issue.

**Comment by jdufresne** [comment]
@dperini v2.2.4 worked for me. Thanks for the quick fix and response!

**Comment by Schnueggel** [comment]
For me 2.2.4 does not work. I use chakra-ui and they use this selector "button:not(:disabled):not([disabled])". I used "resolutions" in package.json to force 2.2.4. My tests still fail. With 2.2.2 they work.

**Comment by dperini** [comment]
@Schnueggel 
for me the above selector you tested works.
It does not throw errors and seems to be working as expected.
To ensure it is working, I successfully checked the following similar selectors permutations:


    document.querySelectorAll('button:not(.disabled)');
    document.querySelectorAll('button:not(:disabled)');
    document.querySelectorAll('button:not([disabled])');

    document.querySelectorAll('button:not(.disabled):not(:disabled)');
    document.querySelectorAll('button:not(.disabled):not([disabled])');
    document.querySelectorAll('button:not(:disabled):not([disabled])');

    document.querySelectorAll('button:not(.disabled):not(:disabled):not([disabled])');

all of them are passing without any parsing error, so I can't say what's wrong on your environment.
I suggest you check  again ensuring your cache is fresh and that you also test with with a different browser.

If you can post a code with the reproducible failing case I will be happy to test it and find a solution.

**Comment by AndresREIB** [comment]
I also use chraka-ui and 2.2.4 also does not work for me. This is what I get:
SyntaxError: ':disabled):not([disabled]' is not a valid selector
I get this when running component tests with jest.
If I override to 2.2.2, it all works fine.

**Comment by Schnueggel** [comment]
newest Chrome supports this syntax. The Problem is the jest testing. The jsdom lib uses nwsapi. I will try to look a bit deeper into things.

**Comment by Schnueggel** [comment]
there comes a list of selectors including this one `:not(:disabled):not([disabled])`

This will compile the following resolver

`
(function anonymous(s
) {
"use strict";return function Resolver(c,f,x,r){var e,n,o,j=r.length-1,k=-1;main:while((e=c[++k])){if(!s.match(":disabled):not([disabled]",e)){r[++j]=c[k];continue main;}}return r;}
})
`

The match function failes then of course

**Comment by giorgosera** [comment]
I have exactly the same issue. I'm also using Chakra and React testing library. I had to use `overrides` like this

```
  "overrides": {
    "nwsapi": "2.2.2"
  },
```
This resolves the issue but I wonder how this can be resolved permanently.

**Comment by mikhin** [comment]
Confirm the problem with Chakra and React testing library.

**Comment by dbashford** [comment]
Also confirming, and for anyone who struggles with it, for overrides to work properly you need npm 8.6.0.

**Comment by zgrybus** [comment]
> I have exactly the same issue. I'm also using Chakra and React testing library. I had to use `overrides` like this
> 
> ```
>   "overrides": {
>     "nwsapi": "2.2.2"
>   },
> ```
> 
> This resolves the issue but I wonder how this can be resolved permanently.

It helped, thanks.
However, I'm looking forward permanent solution.

**Comment by dperini** [comment]
@jdufresne and all developers in this thread/issue,
in commit e60b058 I am trying to fix the :not() pseudo-class bug
Could you please test your specific case is fixed by these changes ?
In cases where this is not fixed please help by reporting the  selector here.

Thank you all for the heads-up, for the suggestions and for the help in solving this bug.

**Comment by GabOsaz** [comment]
> > I have exactly the same issue. I'm also using Chakra and React testing library. I had to use `overrides` like this
> > ```
> >   "overrides": {
> >     "nwsapi": "2.2.2"
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This resolves the issue but I wonder how this can be resolved permanently.
> 
> It helped, thanks. However, I'm looking forward permanent solution.

Worked for me!

**Comment by ttcode10** [comment]
> I have exactly the same issue. I'm also using Chakra and React testing library. I had to use `overrides` like this
> 
> ```
>   "overrides": {
>     "nwsapi": "2.2.2"
>   },
> ```
> 
> This resolves the issue but I wonder how this can be resolved permanently.

Thanks for the solution, but where should we put this script? Thanks

**Comment by nouman-codebrill** [comment]
> > I have exactly the same issue. I'm also using Chakra and React testing library. I had to use `overrides` like this
> > ```
> >   "overrides": {
> >     "nwsapi": "2.2.2"
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This resolves the issue but I wonder how this can be resolved permanently.
> 
> Thanks for the solution, but where should we put this script? Thanks

In the Package.json file below the devDependencies

**Comment by james4388** [comment]
for yarn
```
"resolutions": {
    "**/nwsapi": "2.2.2"
  },
```

**Comment by dperini** [comment]
@jsvossen 
thank you for testing out the latest changes and help ensure this is fixed.
Though you are the only one that answered to my request for help.

So I will have to wait for a couple more confirmation from other developers having issues with other selectors before pushing a new 2.2.5 release on npm.

I really appreciated your input, thank you !

**Comment by dperini** [comment]
@all
please test if the new changes to the Regular Expression works in your cases.
This will be in 2.2.5 as soon as everybody confirm their case is resolved by this change.

**Comment by bfsgr** [comment]
> @jdufresne and all developers in this thread/issue, in commit [e60b058](https://github.com/dperini/nwsapi/commit/e60b058a6d619eb8d0662432e395e4d956883d3b) I am trying to fix the :not() pseudo-class bug Could you please test your specific case is fixed by these changes ? In cases where this is not fixed please help by reporting the selector here.
> 
> Thank you all for the heads-up, for the suggestions and for the help in solving this bug.

I tested this change and so far it seams to fix the problems I was having with Chakra and RTL, thanks!!

**Comment by yarinsa** [comment]
Same for us using @chakra-ui. Downgrading to 2.2.2 worked

**Comment by AttackXiaoJinJin** [comment]
OMG! the bug is still exists in v2.2.16!!
